function [samples, codes] = loadSamplesCT(path_Samples, folder_Samples, tileNameHLS,strName,mask)
    dir_tile = fullfile(path_Samples, folder_Samples);
    
    codes = [1, {'barberry'};...
         2,{'greenbriar'};...
        3,{'mixed_invasive'};...
        4,{'mountain_laurel'};...
        5, {'non_target_shrub'};...
        6,{'sparse_coniferous'};...
        7,{'herbaceous'};...
        8,{'tree_sampling'};...
        9,{'no_understory'}];
    sampImg = imread(fullfile(dir_tile, [tileNameHLS, '_',strName,'.tif']));
    if ~isempty(mask)
        sampImg(mask~=1)=0;
    end
    [row, col] = find(sampImg > 1000 & sampImg ~= 65535);
    ids = zeros(length(row),1);
    for i = 1:length(row)
        ids(i) = sampImg(row(i),col(i));
    end
    type = floor(ids/1000);
    objID = ids;
    samples = [row, col, type, objID];
end
